---

#
# Defaults specified here should not contain
# any secrets or host identifying information.
#

# The Amazon CloudWatch Agent URL
cloudwatch_url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

# Collectd installation parameters
collectd_version: "5.7.2-2ubuntu1"
collectd_install_recommends: yes
