---
# Tests for this role


# Set up #

# To get a baseline comparison for timestamp comparisons
# create a testfile and register its stat info
- name: Create test file
  file: path=testfile state=touch
- name: Stat test file
  stat: path=testfile
  register: testfile


# Tests #
- name: Verify java cmd is using v 1.7
  shell: java -version
  register: java_version
- assert:
    that:
      - "'1.7.0' in java_version.stderr"

# Tear Down #
- name: Remove test file
  file: path=testfile state=absent
