---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role test_build_server
#

#
# vars are namespace with the module name.
#
test_runner_user: jenkins
test_suite_args: ['unit']
test_shard_args: ['shard_1']
edx_platform_base_path: /home/jenkins
clone_repo: yes
