#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Defaults for role devpi
#
---
- name: restart devpi
  supervisorctl: >
    state=restarted
    supervisorctl_path={{ devpi_supervisor_ctl }}
    config={{ devpi_supervisor_cfg }}
    name=devpi-server
  sudo_user: "{{ devpi_supervisor_user }}"
