- name: Deploy portal_designer
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - role: nginx
      nginx_default_sites:
        - portal_designer
    - portal_designer
