---
jenkins_user: "jenkins"
jenkins_group: "jenkins"
jenkins_home: /home/jenkins

# repo for nodejs
jenkins_chrislea_ppa: "ppa:chris-lea/node.js"

# System packages
jenkins_debian_pkgs:
    - nodejs
    - pkg-config

# packer direct download URL
packer_url: "https://dl.bintray.com/mitchellh/packer/0.6.1_linux_amd64.zip"
