# Install browsermob-proxy, which is used for page performance testing with bok-choy
---
- name: get zip file
  get_url: >
    url={{ browsermob_proxy_url }}
    dest=/var/tmp/browsermob-proxy-{{ browsermob_proxy_version }}.zip

- name: unzip into /var/tmp/
  shell: >
    unzip /var/tmp/browsermob-proxy-{{ browsermob_proxy_version }}.zip
    chdir=/var/tmp

- name: move to /etc/browsermob-proxy/
  shell: > 
    mv /var/tmp/browsermob-proxy-{{ browsermob_proxy_version }} /etc/browsermob-proxy

- name: change permissions of main script
  file: >
    path=/etc/browsermob-proxy/bin/browsermob-proxy
    mode=0755

- name: add wrapper script /usr/local/bin/browsermob-proxy
  copy: >
      src=browsermob-proxy
      dest=/usr/local/bin/browsermob-proxy

- name: change permissions of wrapper script
  file: >
      path=/usr/local/bin/browsermob-proxy
      mode=0755
