- name: Deploy common
  hosts: all
  become: True
  gather_facts: True
  vars:
    SECURITY_UNATTENDED_UPGRADES: true
    COMMON_SECURITY_UPDATES: true
  roles:
    - common
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
