#
# Requires MySQL-python be installed for system python
#
- name: Create analtyics reports db
  hosts: all
  connection: local
  gather_facts: False
  tasks:
    # Install required library
    - name: install python mysqldb module
      pip: name={{item}} state=present
      sudo: yes
      with_items:
        - MySQL-python

    - name: create mysql databases for the analytics report API
      mysql_db: >
        db={{ item.key }}
        state={{ item.value.state }}
        encoding={{ item.value.encoding }}        
        login_host={{ item.value.login_host }}
        login_user={{ item.value.login_user }}
        login_password={{ item.value.login_password }}
      with_dict: databases

    - name: create mysql users and assign privileges
      mysql_user: >
        name="{{ item.key }}"
        priv="{{ '/'.join(item.value.privileges) }}"
        password="{{ item.value.password }}"
        host={{ item.value.host }}
        login_host={{ item.value.login_host }}
        login_user={{ item.value.login_user }}
        login_password={{ item.value.login_password }}
        append_privs=yes        
      with_dict: database_users
