- name: Deploy discern
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    enable_datadog: True
    enable_splunkforwarder: True
  vars_files:
    - ["{{ secure_vars }}", "dummy.yml"]
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - discern
    - discern
    - role: datadog
      when: enable_datadog
    - role: splunkforwarder
      when: enable_splunkforwarder
