- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    NGINX_EDXAPP_CUSTOM_REDIRECTS: {}
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - lms
      - cms
      nginx_default_sites:
      - lms
      nginx_redirects: "{{ NGINX_EDXAPP_CUSTOM_REDIRECTS }}"
    - role: nginxtra
      when: NGINXTRA_CONFIGS is defined
    - edxapp
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
