- name: Deploy forum
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    enable_datadog: True
    enable_splunkforwarder: True
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - forum
    - forum
    - role: datadog
      when: enable_datadog
    - role: splunkforwarder
      when: enable_splunkforwarder
