# ansible-playbook -i ./lifecycle_inventory.py ./retire_host.yml 
# -e@/vars/env.yml --limit Terminating_Wait

- name: Server retirement workflow
  hosts: all
  sudo: True
  gather_facts: False
  vars:
    STOP_ALL_EDX_SERVICES_EXTRA_ARGS: "--no-wait"
  roles:
    - stop_all_edx_services
  tasks:
    - name: Force a log rotation
      command: /usr/sbin/logrotate -f /etc/logrotate.d/hourly/tracking.log
    - name: Send logs to s3
      command: /edx/bin/send-logs-to-s3
    - name: Run minos
      command: /edx/app/minos/venvs/bin/minos --config /edx/etc/minos/minos.yml --json
