---
#
# edX Configuration
#
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions

harprofiler_role_name: harprofiler

harprofiler_user: "harprofiler"
harprofiler_github_url: https://github.com/cgoldberg/harprofiler
harprofiler_version: 2958a910cc0c33967f7d7faf4519fa03271fdaf1
harprofiler_dir: /edx/app/harprofiler
