---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role jenkins_admin
# 

#
# vars are namespace with the module name.
#
jenkins_admin_role_name: jenkins_admin

#
# OS packages
#

jenkins_admin_debian_pkgs: []

jenkins_admin_redhat_pkgs: []

jenkins_admin_plugins:
  - { name: "greenballs", version: "1.14" }
  - { name: "rebuild", version: "1.21" }
  - { name: "build-user-vars-plugin", version: "1.1" }
  - { name: "build-token-root", version: "1.1" }

jenkins_admin_jobs:
  - 'backup-jenkins'
  - 'prepare-edxapp'
  - 'prepare-forum'
  - 'build-ami'

JENKINS_ADMIN_NAME: 'default_jenkins_name'

# jenkins_admin also requires other variables that are not defined by default.

# JENKINS_ADMIN_S3_PROFILE: !!null
# JENKINS_ADMIN_CONFIGURATION_REPO: !!null
# JENKINS_ADMIN_CONFIGURATION_SECURE_REPO: !!null
# 
# # Local path to the key to use to checkout secure repos on jenkins and in abbey
# JENKINS_ADMIN_GIT_KEY_LOCAL_PATH: !!null
# 
# # EC2 Key to use when bringing up the abbey instance in ec2 (aws key-pair)
# JENKINS_ADMIN_EC2_KEY: !!null
