---
# Versions of Python newer than 3.5 are not available in the default
# package index for Ubuntu 16.04. Add the deadsnakes PPA for anything
# newer
- name: add deadsnakes PPA for newer Python versions
  apt_repository:
    repo: "ppa:deadsnakes/ppa"
    update_cache: yes
  when: ansible_distribution_release == 'xenial'

# Install newer versions of python for testing, but do not set them
# as the default version
- name: Install python versions
  apt:
    name: 'python{{ item }}'
    state: present
    update_cache: yes
  with_items: '{{ jenkins_worker_python_versions }}'

# Install 'dev' packages for each version of python that is installed
- name: Install python dev packages
  apt:
    name: 'python{{ item }}-dev'
    state: present
    update_cache: yes
  with_items: '{{ jenkins_worker_python_versions }}'

# Install 'distutils' packages for each installed version of python which has one
- name: Install python distutils packages
  apt:
    name: 'python{{ item }}-distutils'
    state: present
    update_cache: yes
  with_items: '{{ jenkins_worker_distutils_versions }}'


- name: Fetch get-pip.py from pypa
  get_url:
    url: "https://bootstrap.pypa.io/get-pip.py"
    dest: "/tmp/get-pip.py"

- name: Install most recent 'pip' for installed python versions 3.6 and greater.
  shell:
    cmd: "python{{ item }} /tmp/get-pip.py"
  when:
    - item != '3.5'
    - item != '2.7'
  with_items: '{{ jenkins_worker_python_versions }}'
  register: python_versions

- name: Install pinned 'pip' for installed python version 3.5 and lower.
  shell:
    cmd: "python{{ item }} /tmp/get-pip.py pip<21.0"
  with_items: '{{ python_versions.results }}'
  when: item | skipped

# Requests library is required for the github status script.
- name: Install requests Python library
  pip:
    name: "{{ common_pip_pkgs + ['requests'] }}"
    state: present
    executable: 'pip{{ item }}'
  with_items: "{{ jenkins_worker_python_versions }}"

