# Iterates over the data structure documented in tasks/main.yml
# checking out the grader code from the repository specified on
# a per queue basis.

- name: checkout grader code
  git: >
    dest={{ xqwatcher_data_dir }}/{{ item.COURSE }} repo={{ item.GIT_REPO }}
    version={{ item.GIT_REF }}
    ssh_opts="{{ xqwatcher_git_ssh_opts }}"
  sudo: true
  sudo_user: "{{ xqwatcher_user }}"
  with_items: XQWATCHER_COURSES
