- name: install read-only ssh key
  copy: >
    content="{{ XQWATCHER_GIT_IDENTITY }}" dest={{ xqwatcher_git_identity }}
    owner={{ xqwatcher_user }} group={{ xqwatcher_user }} mode=0600

- name: remove read-only ssh key for the content repo
  file: path=/tmp/git_ssh.sh state=absent

- include: deploy_watcher.yml
  tags:
    - deploy-watcher
    - deploy

- include: deploy_courses.yml
  tags:
    - deploy-courses
    - deploy

- name: remove read-only ssh key for the content repo
  file: path={{ xqwatcher_git_identity }} state=absent
