---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role sitespeedio
# 
# Overview:
#   Install the sitespeed.io package along with it's dependencies.
#   See http://sitespeed.io/ for details on running.
# 
#
# Dependencies:
#  none
# 
# Example play:
#  role:
#    - sitespeedio
#

# Install Sitespeed Dependencies
- name: install sitespeed.io specific system packages
  apt: pkg={{','.join(sitespeedio_debian_pkgs)}} state=present

- name: install sitespeed.io
  npm: name=sitespeed.io global=yes state=latest
