
base_url: "https://mms.mongodb.com/download/agent/monitoring"
pkg_arch: "amd64"
pkg_format: "deb"

agents:
  - agent: mongodb-mms-monitoring-agent
    version: "4.1.0.251-1"
    config: "/etc/mongodb-mms/monitoring-agent.config"
  - agent: mongodb-mms-backup-agent
    version: "4.1.0.347-1"
    config: "/etc/mongodb-mms/backup-agent.config"
