<<<<<<< HEAD
# this gets all running prod webservers
- hosts: tag_environment_prod_cme:&tag_function_util
# or we can get subsets of them by name
#- hosts: ~tag_Name_util(10)_cme
=======
- name: Basic util setup on cme hosts
  # This uses variable expansion so you can select machine(s) from the command line
  # using the -e flag.  See README for instructions on how to use.
  hosts: ~tag_Name_{{machine}}_cme
  pre_tasks:
  - fail: msg="This playbook only runnable on 'util' machines"
    when: "'util' not in machine"
>>>>>>> ddd57c4... validate machine var, remove migrate_db prompt
  sudo: True
  vars:
    secure_dir: '../../../edx-secret/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../../../../edx-secret/ansible/local'
    migrate_db: "no"
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_cme_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
  roles:
    - common
    - supervisor
    - { role: 'edxapp', celery_worker: True }
