# This uses variable expansion so you can select machine(s) from the command line
# using the -e flag.  See README for instructions on how to use.
- hosts: ~tag_Name_{{machine}}_prod
#
# This alternative hits all running prod webservers.  Left here as an example.
#- hosts: tag_environment_prod:&tag_function_webserver
  sudo: True
  vars_prompt:
    - name: "migrate_db"
      prompt: "Should this playbook run database migrations? (Type 'yes' to run, anything else to skip migrations)"
      default: "no"
      private: no
  vars:
    secure_dir: '../../../configuration-secure/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../configuration-secure/ansible/local'
    not_prod: false
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_prod_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
    - "{{ secure_dir }}/vars/shib_prod_vars.yml"
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
      nginx_default_sites:
      - lms
    - edxapp
    - apache
    - shibboleth
    # run this role last
    - in_production
