---
dependencies:
  - common
  - jscover
  # dependencies for edx-app jenkins worker:
  - role: edxapp_common
    when: platform_worker is defined
  - role: rbenv
    rbenv_user: "{{ jenkins_user }}"
    rbenv_dir: "{{ jenkins_home }}"
    rbenv_ruby_version: "{{ jenkins_ruby_version }}"
    jenkins_worker: true
    when: platform_worker is defined

  # dependencies for sitespeed worker
  - role: sitespeedio
    when: sitespeed_worker is defined
