---

localdev_user: "vagrant"
localdev_home: "/home/vagrant"
localdev_xauthority: "{{ localdev_home }}/.Xauthority"
localdev_xvfb_display: ":1"

localdev_accounts:
    - { user: "{{ edxapp_user|default('None') }}", home: "{{ edxapp_app_dir }}",
        env: "edxapp_env", repo: "edx-platform" }

    - { user: "{{ forum_user|default('None') }}", home: "{{ forum_app_dir }}",
        env: "forum_env", repo: "cs_comments_service" }

    - { user: "{{ ora_user|default('None') }}", home: "{{ ora_app_dir }}",
        env: "ora_env", repo: "ora" }

    - { user: "{{ notifier_user|default('None') }}", home: "{{ notifier_app_dir }}",
        env: "notifier_env", repo: "" }

    - { user: "{{ ecommerce_user|default('None') }}", home: "{{ ecommerce_home }}",
        env: "ecommerce_env", repo: "ecommerce" }

# Helpful system packages for local dev
local_dev_pkgs:
    - vim
    - emacs
    - xorg
    - openbox

localdev_jscover_version: "1.0.2"

localdev_oauth2_clients:
    - { name: "{{ ecommerce_service_name }}", url_root: "{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}",
        id: "{{ ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_KEY }}", secret: "{{ ECOMMERCE_SOCIAL_AUTH_EDX_OIDC_SECRET }}" }
    - { name: "{{ INSIGHTS_OAUTH2_APP_CLIENT_NAME | default('insights') }}", url_root: "{{ INSIGHTS_BASE_URL | default('http://127.0.0.1:8100') }}",
        id: "{{ INSIGHTS_OAUTH2_KEY | default('YOUR_OAUTH2_KEY') }}", secret: "{{ INSIGHTS_OAUTH2_SECRET | default('secret') }}" }
