---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role minos
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: gather ec2 facts
  action: ec2_facts

- name: create minos config directory
  file: >
    path={{ minos_voter_cfg }}
    state=directory
    owner=root
    group=root
    mode=0755
  when: INSTALL_MINOS

- name: create minos config
  template: >
    dest={{ minos_cfg_file }}
    src=edx/etc/minos/minos.yml.j2
    mode=0755 owner=root group=root
  when: INSTALL_MINOS
  
- name: create minos voters configs
  template: >
    dest={{ minos_voter_cfg }}/{{ item }}.yml
    src=edx/etc/minos/conf.d/{{ item }}.yml.j2
    mode=0755 owner=root group=root
  with_items:
    - "BellwetherVoter"
    - "ProccessQuienscenceVoterCelery"
    - "ProccessQuienscenceVoterGunicorn"
    - "TrackingLogVoter"
  when: INSTALL_MINOS

    # Optional auth for git
- name: create ssh script for git (not authenticated)
  template: >
    src=tmp/git-identity.sh.j2 dest={{ minos_git_ssh }}
    mode=750
  when:
    - INSTALL_MINOS
    - MINOS_GIT_IDENTITY is not defined

- name: create ssh script for git (authenticated)
  template: >
    src=tmp/git-identity.sh.j2 dest={{ minos_git_ssh }}
    mode=750
  when:
    - INSTALL_MINOS
    - MINOS_GIT_IDENTITY is defined

- name: install read-only ssh key
  copy: >
    content="{{ COMMON_GIT_IDENTITY }}" dest="{{ minos_git_identity }}"
    force=yes mode=0600
  when: INSTALL_MINOS

- name : install python custom-requirements
  pip: >
    name="{{ item }}"
    virtualenv="{{ minos_venv_dir }}"
    state=present
    extra_args="--exists-action w"
  environment:
    GIT_SSH: "{{ minos_git_ssh }}"
  with_items:
    - "{{ minos_requirement }}"
  when: INSTALL_MINOS