---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role ansible-role-django-ida

dependencies:
  - role: edx_django_service
    edx_django_service_version: '{{ PORTAL_DESIGNER_VERSION }}'
    edx_django_service_name: '{{ portal_designer_service_name }}'
    edx_django_service_config_overrides: '{{ portal_designer_service_config_overrides }}'
    edx_django_service_debian_pkgs_extra: '{{ portal_designer_debian_pkgs }}'
    edx_django_service_gunicorn_port: '{{ portal_designer_gunicorn_port }}'
    edx_django_service_repos: '{{ PORTAL_DESIGNER_REPOS }}'
    edx_django_service_django_settings_module: '{{ PORTAL_DESIGNER_DJANGO_SETTINGS_MODULE }}'
    edx_django_service_environment_extra: '{{ portal_designer_environment }}'
    edx_django_service_gunicorn_extra: '{{ PORTAL_DESIGNER_GUNICORN_EXTRA }}'
    edx_django_service_nginx_port: '{{ PORTAL_DESIGNER_NGINX_PORT }}'
    edx_django_service_ssl_nginx_port: '{{ PORTAL_DESIGNER_SSL_NGINX_PORT }}'
    edx_django_service_language_code: '{{ PORTAL_DESIGNER_LANGUAGE_CODE }}'
    edx_django_service_secret_key: '{{ PORTAL_DESIGNER_SECRET_KEY }}'
    edx_django_service_media_storage_backend: '{{ PORTAL_DESIGNER_MEDIA_STORAGE_BACKEND }}'
    edx_django_service_staticfiles_storage: '{{ PORTAL_DESIGNER_STATICFILES_STORAGE }}'
    edx_django_service_memcache: '{{ PORTAL_DESIGNER_MEMCACHE }}'
    edx_django_service_default_db_host: '{{ PORTAL_DESIGNER_MYSQL_HOST }}'
    edx_django_service_default_db_name: '{{ PORTAL_DESIGNER_DEFAULT_DB_NAME }}'
    edx_django_service_default_db_atomic_requests: false
    edx_django_service_db_user: '{{ PORTAL_DESIGNER_MYSQL_USER }}'
    edx_django_service_db_password: '{{ PORTAL_DESIGNER_MYSQL_PASSWORD }}'
    edx_django_service_extra_apps: '{{ PORTAL_DESIGNER_EXTRA_APPS }}'
    edx_django_service_session_expire_at_browser_close: '{{ PORTAL_DESIGNER_SESSION_EXPIRE_AT_BROWSER_CLOSE }}'
    edx_django_service_social_auth_edx_oauth2_key: '{{ PORTAL_DESIGNER_SOCIAL_AUTH_EDX_OAUTH2_KEY }}'
    edx_django_service_social_auth_edx_oauth2_secret: '{{ PORTAL_DESIGNER_SOCIAL_AUTH_EDX_OAUTH2_SECRET }}'
    edx_django_service_backend_service_edx_oauth2_key: '{{ PORTAL_DESIGNER_BACKEND_SERVICE_EDX_OAUTH2_KEY }}'
    edx_django_service_backend_service_edx_oauth2_secret: '{{ PORTAL_DESIGNER_BACKEND_SERVICE_EDX_OAUTH2_SECRET }}'
    edx_django_service_automated_users: '{{ PORTAL_DESIGNER_AUTOMATED_USERS }}'
    edx_django_service_cors_whitelist: '{{ PORTAL_DESIGNER_CORS_ORIGIN_WHITELIST }}'
    edx_django_service_post_migrate_commands: '{{ portal_designer_post_migrate_commands }}'
    edx_django_service_enable_newrelic_distributed_tracing: '{{ PORTAL_DESIGNER_ENABLE_NEWRELIC_DISTRIBUTED_TRACING }}'
