---
# The deadsnakes PPA is required to install python3.5 on Precise and Trusty.
# Xenial comes with python3.5 installed.
- name: add deadsnakes repository
  apt_repository:
    repo: "ppa:fkrull/deadsnakes"
  when: ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty'
  tags:
    - install
    - install:system-requirements

- name: install python3.5
  apt:
    name: "{{ item }}"
  with_items:
    - python3.5
    - python3.5-dev
  when: ansible_distribution_release == 'precise' or ansible_distribution_release == 'trusty'
  tags:
    - install
    - install:system-requirements

- name: add the mongodb signing key
  apt_key:
    id: "{{ MONGODB_APT_KEY }}"
    keyserver: "{{ MONGODB_APT_KEYSERVER }}"
    state: present
  tags:
    - install
    - install:system-requirements

- name: add the mongodb repo to the sources list
  apt_repository:
    repo: "{{ MONGODB_REPO }}"
    state: present
  tags:
    - install
    - install:system-requirements

- name: install mongo shell
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: yes
    force: yes
    update_cache: yes
  with_items: "{{ mongodb_debian_pkgs }}"
  tags:
    - install
    - install:system-requirements
