---
- name: Add MySQL community apt key
  apt_key:
    id: 8C718D3B5072E1F5
    keyserver: "{{ COMMON_EDX_PPA_KEY_SERVER }}"
    state: present

- name: Install MySQL community apt repositories
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6"
    - "deb-src http://repo.mysql.com/apt/ubuntu/ precise mysql-5.6"

- name: Install mysql-5.6 and dependencies
  apt: 
    name: "{{ item }}" 
    install_recommends: yes
    update_cache: yes
    state: present
  with_items: mysql_debian_pkgs

- name: Start mysql
  service: 
    name: mysql 
    state: started

- name: Ensure Anonymous user(s) does not exist
  mysql_user: 
    name: '' 
    host: "{{ item }}" 
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
