---
dependencies:
  - common
  - supervisor
  - edxapp_common
  - nltk
  - role: edx_themes
    theme_users:
      - "{{ edxapp_user }}"
    additional_theme_dirs:
      - "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS }}"
    when: "{{ EDXAPP_ENABLE_COMPREHENSIVE_THEMING }}"
