---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role aws
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: install system packages
  apt: >
    pkg={{','.join(aws_debian_pkgs)}}
    state=present
    update_cache=yes

- name: install aws python packages
  pip: >
    name="{{ item }}" state=present
    extra_args="-i {{ COMMON_PYPI_MIRROR_URL }}"
  with_items: aws_pip_pkgs

- name: create data directory
  file: >
    path={{ aws_data_dir }}
    state=directory
    owner=root
    group=root
    mode=0700

- name: dump all vars to yaml
  template: src=dumpall.yml.j2 dest={{ aws_var_file }} mode=0600

- name: create symlink for config file
  file: >
    src={{ aws_var_file }}
    dest={{ COMMON_BIN_DIR }}/{{ aws_var_file|basename }}
    state=link

- name: clean up var file, removing all version vars and internal ansible vars
  shell: sed -i -e "/{{item}}/d" {{ edx_ansible_var_file }}
  with_items:
    # deploy versions
    - "^edx_platform_version:"
    - "^edx_platform_commit:"
    - "^xqueue_version:"
    - "^forum_version:"
    - "^xserver_version:"
    - "^discern_ease_version:"
    - "^ora_ease_version:"
    - "^discern_version:"
    - "^ora_version:"
    - "^configuration_version:"
    - "^ease_version:"
    - "^certs_version:"
    # other misc vars
    - "^tags:"
    - "^_original_file:"
    - "^register:"
    - "^item:"
    - "^failed_when:"
    - "^changed_when:"
    - "^delegate_to:"
    - "^ansible_ssh_private_key_file:"
    - "^always_run:"
