# Install docker-engine and docker-compose
# Add users to docker group
---
- name: add docker group
  group:
    name: "{{ docker_group }}"

- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_users }}"

- name: install package dependencies
  apt:
    name: "{{ docker_tools_deps_deb_pkgs }}"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"

- name: add docker apt key
  apt_key:
    keyserver: "{{ docker_apt_keyserver }}"
    id: "{{ docker_apt_key_id }}"

- name: add docker repo
  apt_repository:
    repo: "{{ docker_repo }}"

- name: install docker-engine
  apt:
    name: "docker-engine"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: install docker-compose
  pip:
    name: "docker-compose"
