- name: Deploy edX designer
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: True
    CLUSTER_NAME: 'catalog'
  roles:
    - aws
    - role: nginx
      nginx_default_sites:
        - catalog
    - catalog
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: hermes
      hermes_target_service: 'catalog'
      when: DESIGNER_HERMES_ENABLED
