- name: Deploy edX portal_designer
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: True
    CLUSTER_NAME: 'portal_designer'
  roles:
    - aws
    - role: nginx
      nginx_default_sites:
        - portal_designer
    - portal_designer
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
