- name: Deploy edX Prospectus Service
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'prospectus'
    PROSPECTUS_DATA_DIR: "/edx/var/prospectus"
  roles:
    - role: nginx
      nginx_app_dir: "/etc/nginx"
      nginx_sites:
      - prospectus
      nginx_default_sites:
      - prospectus
      PROSPECTUS_NGINX_PORT: 8000
      NGINX_ROBOT_RULES:
      -
        agent: '*'
        disallow: '/'
    - role: prospectus
